import React from 'react';

const Tips = () => {
  return (
    <div>
      <p>
        Here is going to be some tips generated by AI to suggest how you can improve your eating
        habits and become healthier. It is personalised to your intake and body so you can have a
        piece of mind that you are eating the right amount of nutrients.
      </p>
    </div>
  );
};

export default Tips;
